### ISSUE TITLE
群服互相转发问题

### ISSUE THREAD

**Issue by JKGouZi** [LoosePrince/PF-GUGUBot#67]
群可以向服务器转发，但是服务器不能向群转发
而且 后台会报错
[MCDR] [21:24:39] [TaskExecutor/ERROR]: Error invoking listener EventListener(plugin='gugubot@1.1.2', callback=<function on_user_info at 0x0000022FF7011260>, priori
ty=1000)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 737, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\GUGUbot-v1.1.2.mcdr\gugubot\__init__.py", line 95, in on_user_info
    qq_bot.send_msg_to_qq(server, info)
  File "plugins\GUGUbot-v1.1.2.mcdr\gugubot\bot.py", line 731, in send_msg_to_qq
    self.send_msg_to_all_qq(message)
  File "plugins\GUGUbot-v1.1.2.mcdr\gugubot\bot.py", line 810, in send_msg_to_all_qq
    self.send_group_msg(msg, group)
  File "plugins\GUGUbot-v1.1.2.mcdr\gugubot\bot.py", line 803, in send_group_msg
    self.bot.send_group_msg(group, msg)
  File "plugins\cq_qq_api-v1.0.1.mcdr\cq_qq_api\bot.py", line 123, in send_group_msg
    "group_id": int(group_id),
                ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by XueK66** [comment]
谢谢使用gugubot并提交issue！

从您的错误报告来看，是 config 中的 **group_id** 没有设置或是格式问题， 导致报错。
可能的解决方案：参考本仓库的 default_config.yml 设置 group_id。

抱歉啦，我们后续会优化这个地方的报错提示！

**Comment by XueK66** [comment]
已使用config_default.yml解决问题
